### ISSUE TITLE
data error on frontend (mapbox)

### ISSUE THREAD

**Issue by HerziPinki** [Wikimedia-Austria/WikiDaheim#132] opened 2023-05-23 20:06 UTC
Matrei am Brenner, Mühlbachl and Pfons have been merged to new Matrei am Brenner with beginning of 2021. This is not reflected in the frontend, where Matrei am Brenner, Mühlbachl and Pfons are considered to be three separate municipalities. The merge was also accompanied with a new GKZ 70370.
I have now changed the GKZ in https://de.wikipedia.org/w/index.php?title=Liste_der_denkmalgesch%C3%BCtzten_Objekte_in_Matrei_am_Brenner-Matrei&diff=prev&oldid=233975923&diffmode=source and I also changed
https://www.wikidata.org/w/index.php?title=Q429728&diff=1901611743&oldid=1887696220&diffmode=source

The Denkmallisten for Mühlbachl and Pfons already had the GKZ 70370.

The more general problem is how to stay up-to-date with such changes.

**Comment by HerziPinki** [comment] 2023-05-23 20:23
see more municipality changes on https://de.wikipedia.org/wiki/Wikipedia:WikiProjekt_%C3%96sterreich/Liste_von_Umbenennungen_%C3%B6sterreichischer_Gemeinden

**Comment by reiterbene** [comment] 2023-05-24 17:35
Duplicate of #131

**Closed by reiterbene** 2023-05-24 17:35 UTC
Labels: bug
